/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "on-error": "#690005",
        "inverse-surface": "#e5e1e4",
        "on-secondary-fixed": "#07006c",
        "on-surface": "#e5e1e4",
        "primary": "#44edb7",
        "on-background": "#e5e1e4",
        "surface-tint": "#2fe0aa",
        "inverse-primary": "#006c4f",
        "on-error-container": "#ffdad6",
        "on-primary-fixed-variant": "#00513b",
        "primary-container": "#00d09c",
        "on-primary-fixed": "#002116",
        "secondary-fixed-dim": "#c0c1ff",
        "secondary-container": "#3131c0",
        "on-tertiary": "#2f3132",
        "tertiary": "#d2d3d5",
        "surface-container-highest": "#353437",
        "on-tertiary-fixed-variant": "#454749",
        "inverse-on-surface": "#313032",
        "surface": "#131315",
        "outline": "#85948c",
        "surface-dim": "#131315",
        "on-primary": "#003828",
        "on-tertiary-container": "#46484a",
        "surface-bright": "#39393b",
        "on-surface-variant": "#bacac1",
        "tertiary-fixed-dim": "#c6c6c8",
        "background": "#131315",
        "surface-container-high": "#2a2a2c",
        "secondary-fixed": "#e1e0ff",
        "surface-variant": "#353437",
        "surface-container-lowest": "#0e0e10",
        "on-secondary": "#1000a9",
        "on-secondary-fixed-variant": "#2f2ebe",
        "outline-variant": "#3c4a43",
        "surface-container-low": "#1c1b1d",
        "error": "#ffb4ab",
        "surface-container": "#201f21",
        "tertiary-container": "#b6b7b9",
        "on-tertiary-fixed": "#1a1c1d",
        "secondary": "#c0c1ff",
        "on-primary-container": "#00533c",
        "error-container": "#93000a",
        "tertiary-fixed": "#e2e2e4",
        "on-secondary-container": "#b0b2ff",
        "primary-fixed-dim": "#2fe0aa",
        "primary-fixed": "#59fdc5"
      },
      borderRadius: {
        "DEFAULT": "0.25rem",
        "lg": "0.5rem",
        "xl": "0.75rem",
        "full": "9999px"
      },
      spacing: {
        "base": "8px",
        "margin-mobile": "16px",
        "card-gap": "24px",
        "gutter": "24px",
        "container-padding": "32px"
      },
      fontFamily: {
        "display-lg": ["Inter", "sans-serif"],
        "body-lg": ["Inter", "sans-serif"],
        "label-sm": ["Inter", "sans-serif"],
        "headline-lg-mobile": ["Inter", "sans-serif"],
        "body-md": ["Inter", "sans-serif"],
        "label-md": ["Inter", "sans-serif"],
        "headline-md": ["Inter", "sans-serif"],
        "headline-lg": ["Inter", "sans-serif"]
      },
      fontSize: {
        "display-lg": ["48px", { "lineHeight": "56px", "letterSpacing": "-0.02em", "fontWeight": "800" }],
        "body-lg": ["18px", { "lineHeight": "28px", "fontWeight": "400" }],
        "label-sm": ["12px", { "lineHeight": "16px", "letterSpacing": "0.05em", "fontWeight": "700" }],
        "headline-lg-mobile": ["24px", { "lineHeight": "32px", "fontWeight": "700" }],
        "body-md": ["16px", { "lineHeight": "24px", "fontWeight": "400" }],
        "label-md": ["14px", { "lineHeight": "20px", "letterSpacing": "0.02em", "fontWeight": "600" }],
        "headline-md": ["24px", { "lineHeight": "32px", "fontWeight": "600" }],
        "headline-lg": ["32px", { "lineHeight": "40px", "letterSpacing": "-0.01em", "fontWeight": "700" }]
      }
    },
  },
  plugins: [],
}
