from pulse.models.domain import PulseReport

def render_markdown_doc(report: PulseReport) -> str:
    """
    Renders a PulseReport into a Markdown string for a Google Doc.
    """
    lines = []
    
    # Header
    lines.append(f"# Pulse Report: {report.product_name}")
    lines.append(f"**Period:** {report.start_date.strftime('%Y-%m-%d')} to {report.end_date.strftime('%Y-%m-%d')}")
    lines.append("")
    lines.append("---")
    lines.append("")
    
    # Themes
    for theme in report.themes:
        lines.append(f"## {theme.theme_name}")
        lines.append(f"**Summary:** {theme.theme_summary}")
        lines.append("")
        
        if theme.quotes:
            lines.append("### Key Quotes")
            for quote in theme.quotes:
                lines.append(f"> \"{quote}\"")
            lines.append("")
            
        if theme.action_ideas:
            lines.append("### Action Ideas")
            for action in theme.action_ideas:
                lines.append(f"- {action}")
            lines.append("")
            
        lines.append("---")
        lines.append("")
        
    return "\n".join(lines)

def render_email_html(report: PulseReport, doc_link: str) -> str:
    """
    Renders a sleek HTML email body summarizing the report.
    """
    themes_html = ""
    for theme in report.themes:
        themes_html += f"<li><strong>{theme.theme_name}:</strong> {theme.theme_summary}</li>"
        
    html = f"""
    <html>
      <body style="font-family: Arial, sans-serif; line-height: 1.6; color: #333;">
        <h2 style="color: #2c3e50;">Pulse Report: {report.product_name}</h2>
        <p>The latest weekly review pulse is ready. We analyzed reviews from <strong>{report.start_date.strftime('%b %d, %Y')}</strong> to <strong>{report.end_date.strftime('%b %d, %Y')}</strong>.</p>
        
        <h3>Top Themes Discovered:</h3>
        <ul>
          {themes_html}
        </ul>
        
        <div style="margin-top: 20px; padding: 15px; background-color: #f8f9fa; border-left: 4px solid #007bff;">
            <p style="margin: 0;"><strong>View Full Report:</strong> <a href="{doc_link}" style="color: #007bff; text-decoration: none; font-weight: bold;">Open Google Doc</a></p>
        </div>
        
        <p style="margin-top: 30px; font-size: 0.9em; color: #7f8c8d;">
          This is an automated report generated by the Weekly Product Review Pulse system.
        </p>
      </body>
    </html>
    """
    return html
